### ISSUE TITLE
Support git-hooks

### ISSUE THREAD

**Issue by sanyavertolet** [teamvolik/teamvolik#2]
We need to support git hooks in order to forbid creating branches that do not start with `feature/`/`bugfix/`/`hotfix/`. Do something like that:
```
#!/usr/bin/env bash

branch_name="$(git rev-parse --abbrev-ref HEAD)"
branch_pattern="^(feature|bugfix|hotfix)/.*$"
error_message="Your branch name doesn't match the pattern $branch_pattern. Please correct it before committing."

if [[ ! $branch_name =~ $branch_pattern ]]
then
  echo "$error_message"
  exit 1
fi

exit 0
```
We also might want to set a pattern for commit message. This can be done with:
```
#!/usr/bin/env bash

commit_pattern="(Merge (remote-tracking )?branch|### What's done:)"
error_msg="Your commit message doesn't match the pattern $commit_pattern. Please fix it."

if [[ ! $( cat "$1" ) =~ $commit_pattern ]]
then
    echo "$error_msg"
    exit 1
fi

exit 0
```

**Comment by sanyavertolet** [comment]
[Here](https://habr.com/ru/post/302932/) is something that might work

**Comment by dgreflex** [comment]
@sanyavertolet [Here](https://habr.com/ru/post/302932/) it is suggested to use hooks manually, which is inconvenient. In turn, it is impossible to make a custom config that will be automatically applied due to security policy. Therefore, the easiest way has been and will be either a script that will edit the config in the local repository, or manually write "git config core.hooksPath .git-hooks" what will work as well.
