### ISSUE TITLE
Create an initial version of the bot

### ISSUE THREAD

**Issue by dgreflex** [teamvolik/teamvolik#7]
It is required to modify echo-bot and get the initial version of the bot from it, which should:
- Have a basic set of commands
- Know how to work with a database
- Additional features for convenient administration

**Comment by sanyavertolet** [comment]
First of all we need to implement signing up in our bot.
Just a simple "Hello put ur Name 'n' Surname pls".
Later we will support dialog to create game.

**Comment by sanyavertolet** [comment]
And move `bot.py` file to `src/bot` and add some tests to `test`. Talking about tests I hope you will do something. Maybe it is a good idea to look through the source code of `python-telegram-bot`. I am more than sure that they do have tests there.

**Comment by sanyavertolet** [comment]
I look at file `src/bot/main.py` and start crying because of a long file. Maybe we should split functions that create games into one file, functions that allow users to sign up for a game into another and so on. We also should leave conversation handler and the main part of the bot in `src/bot/main.py`
